version: '3.8'

services:

  # Apache Solr
  solr:
      image: solr:latest
      container_name: solr
      ports:
      - "8983:8983"
      volumes:
      - ./solr-data:/var/solr
      command:
        - solr-precreate
        - restaurant-service
      networks:
      - app-network

  # PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=n11-final-review-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "log-topic:1:1"
    networks:
      - app-network

  # Restaurant Service
  restaurant-service:
    build:
      context: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "8081:8081"
    depends_on:
      - solr
    environment:
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - SOLR_CORE_NAME=restaurant-service
    networks:
      - app-network

  # Review Service
  review-service:
    build:
      context: ./review-service
    container_name: review-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/n11-final-review-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
