version: '3.8'

services:

  postgres_review:
    image: postgres:latest
    container_name: postgres_review
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=n11-final-review-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data/review:/var/lib/postgresql/data
    networks:
      - app-network

  # PostgreSQL for n11-final-logging-service
  postgres_logging:
    image: postgres:latest
    container_name: postgres_logging
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=n11-final-logging-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data/logging:/var/lib/postgresql/data
    networks:
      - app-network
  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  # Kafka
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "log-topic:1:1"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
